spring:
  application:
    name: librarymanager

  datasource:
    url: jdbc:postgresql://localhost:5431/librarymanager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

librarymanager:
  security:
    secret: "8f6760ab700b1a09b93356ba47e2cfc7e6f1af7baf9e1f7ce4dd44b97a45b328"